-- Performance OS durable storage tables.
-- These JSONB-backed tables preserve the current app data shape while moving
-- real user data out of local CSV/JSON files for production.

CREATE TABLE IF NOT EXISTS food_logs (id BIGSERIAL PRIMARY KEY, row_order INTEGER NOT NULL DEFAULT 0, data JSONB NOT NULL, created_at TIMESTAMPTZ NOT NULL DEFAULT now(), updated_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS frequent_foods (id BIGSERIAL PRIMARY KEY, row_order INTEGER NOT NULL DEFAULT 0, data JSONB NOT NULL, created_at TIMESTAMPTZ NOT NULL DEFAULT now(), updated_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS food_shortcuts (id BIGSERIAL PRIMARY KEY, row_order INTEGER NOT NULL DEFAULT 0, data JSONB NOT NULL, created_at TIMESTAMPTZ NOT NULL DEFAULT now(), updated_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS meal_templates (id BIGSERIAL PRIMARY KEY, row_order INTEGER NOT NULL DEFAULT 0, data JSONB NOT NULL, created_at TIMESTAMPTZ NOT NULL DEFAULT now(), updated_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS body_metric_logs (id BIGSERIAL PRIMARY KEY, row_order INTEGER NOT NULL DEFAULT 0, data JSONB NOT NULL, created_at TIMESTAMPTZ NOT NULL DEFAULT now(), updated_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS workout_logs (id BIGSERIAL PRIMARY KEY, row_order INTEGER NOT NULL DEFAULT 0, data JSONB NOT NULL, created_at TIMESTAMPTZ NOT NULL DEFAULT now(), updated_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS recovery_logs (id BIGSERIAL PRIMARY KEY, row_order INTEGER NOT NULL DEFAULT 0, data JSONB NOT NULL, created_at TIMESTAMPTZ NOT NULL DEFAULT now(), updated_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS sleep_logs (id BIGSERIAL PRIMARY KEY, row_order INTEGER NOT NULL DEFAULT 0, data JSONB NOT NULL, created_at TIMESTAMPTZ NOT NULL DEFAULT now(), updated_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS daily_nutrition_summaries (id BIGSERIAL PRIMARY KEY, row_order INTEGER NOT NULL DEFAULT 0, data JSONB NOT NULL, created_at TIMESTAMPTZ NOT NULL DEFAULT now(), updated_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS api_connections (id BIGSERIAL PRIMARY KEY, row_order INTEGER NOT NULL DEFAULT 0, data JSONB NOT NULL, created_at TIMESTAMPTZ NOT NULL DEFAULT now(), updated_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS macro_targets (id BIGSERIAL PRIMARY KEY, row_order INTEGER NOT NULL DEFAULT 0, data JSONB NOT NULL, created_at TIMESTAMPTZ NOT NULL DEFAULT now(), updated_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS user_goal_settings (id BIGSERIAL PRIMARY KEY, row_order INTEGER NOT NULL DEFAULT 0, data JSONB NOT NULL, created_at TIMESTAMPTZ NOT NULL DEFAULT now(), updated_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS personal_records (id BIGSERIAL PRIMARY KEY, row_order INTEGER NOT NULL DEFAULT 0, data JSONB NOT NULL, created_at TIMESTAMPTZ NOT NULL DEFAULT now(), updated_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS integration_sync_state (id BIGSERIAL PRIMARY KEY, row_order INTEGER NOT NULL DEFAULT 0, data JSONB NOT NULL, created_at TIMESTAMPTZ NOT NULL DEFAULT now(), updated_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS ai_food_cache (id BIGSERIAL PRIMARY KEY, row_order INTEGER NOT NULL DEFAULT 0, data JSONB NOT NULL, created_at TIMESTAMPTZ NOT NULL DEFAULT now(), updated_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS usda_food_cache (id BIGSERIAL PRIMARY KEY, row_order INTEGER NOT NULL DEFAULT 0, data JSONB NOT NULL, created_at TIMESTAMPTZ NOT NULL DEFAULT now(), updated_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS verified_food_cache (id BIGSERIAL PRIMARY KEY, row_order INTEGER NOT NULL DEFAULT 0, data JSONB NOT NULL, created_at TIMESTAMPTZ NOT NULL DEFAULT now(), updated_at TIMESTAMPTZ NOT NULL DEFAULT now());

CREATE INDEX IF NOT EXISTS food_logs_row_order_idx ON food_logs (row_order);
CREATE INDEX IF NOT EXISTS meal_templates_row_order_idx ON meal_templates (row_order);
CREATE INDEX IF NOT EXISTS body_metric_logs_row_order_idx ON body_metric_logs (row_order);
CREATE INDEX IF NOT EXISTS workout_logs_row_order_idx ON workout_logs (row_order);
CREATE INDEX IF NOT EXISTS recovery_logs_row_order_idx ON recovery_logs (row_order);
CREATE INDEX IF NOT EXISTS sleep_logs_row_order_idx ON sleep_logs (row_order);
